### ISSUE TITLE
IdeaPad 5 15ARE05: Options showing incorrect status.

### ISSUE THREAD

**Issue by Jammyjamjamman** [theorlangur/ideapad5_14are05_energy_mgmt#1]
All the options appear to work on the lenovo Ideapad 5 15 👍. However:

* `ideapad5_14are05_energy_mgmt.sh perf_mode` always shows the performance status as "perf".
* `batt_conserv` `rapid_charge` status always appear as "off".

**Comment by theorlangur** [comment]
well it's ideapad 5 15 after all, not 14 :)
the thing is, it seems that ACPI interface for changing these settings is pretty much similar across various Lenovo models,
the bits that are set, however, appear to be different for different models.
so what one should do is get a decompiled DSDT table for IdeaPad 5 15 and analyze which bits get affected by calls described [here](https://wiki.archlinux.org/index.php/Lenovo_IdeaPad_5_14are05#System_Performance_Mode)

**Comment by Jammyjamjamman** [comment]
Thanks for the help. It looks like someone has already posted the options for my laptop too: https://wiki.archlinux.org/index.php/Lenovo_IdeaPad_5_15are05#System_Performance_Mode

It also happens to be that the flags for setting the options are the same for the 14 and the 15, but the flags for getting settings are different. Hence my problem.

**Comment by theorlangur** [comment]
it's actually great that somebody has already done the research part. This means that in theory with few adjustments you could make the script work for your ideapad 5 15.
Probably `get_bit` function should be adjusted for '0x2' case and correspondingly `perf_mode`, `rapid_charge` and `battery_conservation` functions to poll the correct bit(s).
